name: Park Imminent
markdown: kramdown
collections:
  about:
    output: true
  recipes:
    output: true
  common-lisp:
    output: true
  woodworking:
    output: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "article"
