name: Park Imminent
markdown: kramdown
collections:
  about:
    output: true
    title: About
  recipes:
    output: true
    title: Cooking and recipes
  programming:
    output: true
    title: Programming
  sailing:
    output: true
    title: Sailing
  misc:
    output: true
    title: Miscellaneous
  unstarted:
    output: true
    title: Ideas and unstarted projects
  language:
    output: true
    title: Language
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "article-v2"
