Index
<ul class='col2 capital'>
<li><a href='spectrum-pi.pil'>Spectrum PI</a></li>
<li><a href='boat-to-do.pil'>Boat to do list</a></li>
<li><a href='vegan-melbourne.pil'>Vegan food in Melbourne</a></li>
<li><a href='sweet-pepper-salad.pil'>Sweet pepper salad</a></li>
<li><a href='amulet-vm.pil'>Amulet VM</a></li>
<li><a href='testing.pil'>Test pages</a></li>
<li><a href='soba.pil'>Soba</a></li>
<li><a href='tomato-relish.pil'>Tomato relish</a></li>
<li><a href='black-pepper-tofu.pil'>Black pepper tofu</a></li>
<li><a href='warrigal-greens-pita.pil'>Spanakopita with warrigal greens</a></li>
<li><a href='low-poly.pil'>Low poly 3D</a></li>
<li><a href='chilli-oil.pil'>Chilli oil</a></li>
<li><a href='roast-potatoes.pil'>Roast potatoes</a></li>
<li><a href='roast-tomato-soup.pil'>Roast tomato soup</a></li>
<li><a href='starflake.pil'>Starflake</a></li>
<li><a href='index.pil'>Index</a></li>
<li><a href='codex.pil'></a></li>
<li><a href='pretzel-dogs.pil'>Pretzel dogs</a></li>
<li><a href='oatmeal-biscuits.pil'>Oatmeal biscuits</a></li>
<li><a href='untested-recipes.pil'>Untested recipes</a></li>
<li><a href='reading-list.pil'>Reading list</a></li>
<li><a href='journal.pil'>date   mrhs ph topic              work type     img caption, ot</a></li>
<li><a href='silver-down-below.pil'>And there's silver down below where the herring fishes go</a></li>
<li><a href='lazy-bread.pil'>Lazy bread</a></li>
<li><a href='nifty.pil'>Nifty</a></li>
<li><a href='lemon-cake.pil'>Lemon cake</a></li>
<li><a href='corn-congee.pil'>Corn congee</a></li>
<li><a href='fennel-rice.pil'>Fennel rice</a></li>
<li><a href='games.pil'>Games</a></li>
<li><a href='zeruda-no-densetsu.pil'>ゼルダの伝説</a></li>
<li><a href='peanut-butter-biscuits.pil'>Peanut butter biscuits</a></li>
<li><a href='japanese-reference.pil'>Japanese notes (full)</a></li>
<li><a href='links.pil'>Links</a></li>
<li><a href='index.html'>Index</a></li>
</ul>